return {
  require("plugins.treesitter"),
  require("plugins.colorscheme"),
  require("plugins.lual"),
  require("plugins.autopairs_comp"),
  require("plugins.tlscp_cmdline"),
  require("plugins.smoothcursor"),
  require("plugins.nvim-cmp"),
  require("plugins.vim-test"),
  require("plugins.colorizer"),
  require("plugins.comment"),
  require("plugins.twilight"),
  require("plugins.harpoon"),
  require("plugins.multicursor"),
}
